server:
  # 自定义端口号
  port: 8088


spring:
  application:
    # 服务提供者
    name: consumer-server

  cloud:
    nacos:
      discovery:
        # 注册到nacos注册中心
        server-addr: 127.0.0.1:8848
#        namespace: 8840cdc5-49dc-4784-9601-199baa1e8704
        cluster-name: ChongQing


#  docker run --name myNginxNacos -p 8848:80  -v /usr/local/nginx/nginx.conf:/etc/nginx/nginx.conf  -v /usr/local/nginx//html:/usr/share/nginx/html -v /usr/local/nginx/logs:/var/log/nginx -d nginx
